import { VocabularyItem } from './types';

// Define word families to avoid consecutive appearance
const wordFamilies: Record<string, string> = {
  // B3L1
  'employ': 'employ',
  'employer': 'employ',
  'employee': 'employ',
  'employment': 'employ',
  'corporation': 'corporation',
  'corporate': 'corporation',
  'illness': 'illness',
  'ill': 'illness',
  'tremendously': 'tremendous',
  'tremendous': 'tremendous',
  'laughter': 'laughter',
  'frighten': 'fright',
  'fright': 'fright',
  'contact': 'contact',
  'germ': 'germ',
  'warmth': 'warmth',
  'frail': 'frail',
  'prompt': 'prompt',
  'confine': 'confine',
  'sparkle': 'sparkle',
  'hug': 'hug',
  'drowsy': 'drowsy',
  'stretch': 'stretch',
  'refuse': 'refuse',
  'refusal': 'refuse',
  'hesitate': 'hesitate',
  'hesitation': 'hesitate',

  // B3L2
  'innovative': 'innovate',
  'innovate': 'innovate',
  'innovation': 'innovate',
  'promise': 'promise',
  'material': 'material',
  'mention': 'mention',
  'structure': 'structure',
  'capable': 'capable',
  'capability': 'capable',
  'collaborate': 'collaborate',
  'collaboration': 'collaborate',
  'architect': 'architect',
  'architecture': 'architect',
  'graduate': 'graduate',
  'graduation': 'graduate',
  'construct': 'construct',
  'construction': 'construct',
  'constructive': 'construct',
  'slightly': 'slight',
  'slight': 'slight',
  'rank': 'rank',
  'ranking': 'rank',
  'unique': 'unique',
  'adjust': 'adjust',
  'adjustment': 'adjust',
  'rely': 'rely',
  'reliable': 'rely',
  'feedback': 'feedback',
  'element': 'element',
  'elementary': 'element',
  'stability': 'stable',
  'stable': 'stable',
  'route': 'route',
  'explore': 'explore',
  'exploration': 'explore',

  // B3L3
  'universe': 'universe',
  'universal': 'universe',
  'generous': 'generous',
  'generosity': 'generous',
  'conflict': 'conflict',
  'distribution': 'distribute',
  'distribute': 'distribute',
  'benefit': 'benefit',
  'beneficial': 'benefit',
  'slaughter': 'slaughter',
  'freeze': 'freeze',
  'miserable': 'miserable',
  'misery': 'miserable',
  'furious': 'furious',
  'fury': 'furious',
  'theft': 'theft',
  'punish': 'punish',
  'punishment': 'punish',
  'banish': 'banish',
  'banishment': 'banish',
  'torture': 'torture',

  // B3L4
  'joyous': 'joy',
  'accompany': 'company',
  'company': 'company',
  'essential': 'essential',
  'mourn': 'mourn',
  'mournful': 'mourn',
  'sorrow': 'sorrow',
  'sorrowful': 'sorrow',
  'occasion': 'occasion',
  'occasional': 'occasion',
  'reunion': 'reunion',
  'reunite': 'reunion',
  'anticipate': 'anticipate',
  'anticipation': 'anticipate',
  'arrival': 'arrive',
  'decorate': 'decorate',
  'decoration': 'decorate',
  'preference': 'prefer',
  'prefer': 'prefer',
  'reception': 'reception',
  'receptionist': 'reception',
  'feast': 'feast',
  'transform': 'transform',
  'transformation': 'transform',
  'resemble': 'resemble',
  'resemblance': 'resemble',
  'participate': 'participate',
  'participation': 'participate',
  'recognize': 'recognize',
  'recognition': 'recognize',
  'inevitable': 'inevitable',
  'escape': 'escape',

  // B3L5
  'blossom': 'blossom',
  'rustle': 'rustle',
  'landscape': 'landscape',
  'splendor': 'splendor',
  'splendid': 'splendor',
  'previously': 'previous',
  'previous': 'previous',
  'capital': 'capital',
  'boast': 'boast',
  'historic': 'historic',
  'historical': 'historic',
  'historian': 'historic',
  'entrance': 'entrance',
  'magnificent': 'magnificent',
  'breathtaking': 'breathtaking',
  'leisurely': 'leisure',
  'leisure': 'leisure',
  'stunning': 'stun',
  'stun': 'stun',
  'delicate': 'delicate',
  'delicacy': 'delicate',
  'distinctive': 'distinct',
  'distinction': 'distinct',
  'distinct': 'distinct',
  'elegant': 'elegant',
  'elegance': 'elegant',
  'appearance': 'appear',
  'appear': 'appear',
  'literature': 'literature',
  'literary': 'literature',
  'deliberate': 'deliberate',
  'destination': 'destination',

  // B3L6
  'slope': 'slope',
  'tumble': 'tumble',
  'bruised': 'bruise',
  'bruise': 'bruise',
  'superior': 'superior',
  'superiority': 'superior',
  'intimately': 'intimate',
  'intimate': 'intimate',
  'intimacy': 'intimate',
  'skillfully': 'skillful',
  'skillful': 'skillful',
  'crop': 'crop',
  'path': 'path',
  'navigate': 'navigate',
  'navigation': 'navigate',
  'outsider': 'outsider',
  'adapt': 'adapt',
  'adaptation': 'adapt',
  'cling': 'cling',
  'twinkle': 'twinkle',
  'pity': 'pity',
  'awe': 'awe',
  'smoothness': 'smooth',
  'smooth': 'smooth',
  'opposition': 'oppose',
  'oppose': 'oppose',
  'peculiar': 'peculiar',
  'confront': 'confront',
  'confrontation': 'confront',
  'dilemma': 'dilemma',
  'nevertheless': 'nevertheless',
  'gaze': 'gaze',
  'envision': 'envision',
  'flee': 'flee',

  // B3L7
  'theory': 'theory',
  'theoretical': 'theory',
  'psychology': 'psychology',
  'psychological': 'psychology',
  'demonstrate': 'demonstrate',
  'demonstration': 'demonstrate',
  'interpret': 'interpret',
  'interpretation': 'interpret',
  'stiff': 'stiff',
  'scratch': 'scratch',
  'exhibit': 'exhibit',
  'exhibition': 'exhibit',
  'gesture': 'gesture',
  'moreover': 'moreover',
  'conscious': 'conscious',
  'consciousness': 'conscious',
  'observe': 'observe',
  'observation': 'observe',
  'reverse': 'reverse',
  'significant': 'significant',
  'significance': 'significant',
  'circumstance': 'circumstance',
  'initially': 'initial',
  'initial': 'initial',
  'glance': 'glance',
  'automatically': 'automatic',
  'automatic': 'automatic',
  'track': 'track',
  'adore': 'adore',
  'affection': 'affection',
  'interact': 'interact',
  'interaction': 'interact',
  'meaningful': 'meaningful',
  'fellow': 'fellow',

  // B3L8
  'abuse': 'abuse',
  'highlight': 'highlight',
  'economy': 'economy',
  'economic': 'economy',
  'economical': 'economy',
  'demand': 'demand',
  'illegally': 'illegal',
  'illegal': 'illegal',
  'legal': 'illegal',
  'lure': 'lure',
  'herd': 'herd',
  'brutal': 'brutal',
  'operator': 'operate',
  'operate': 'operate',
  'operation': 'operate',
  'mercilessly': 'mercy',
  'merciless': 'mercy',
  'mercy': 'mercy',
  'strike': 'strike',
  'commit': 'commit',
  'commitment': 'commit',
  'obedient': 'obedient',
  'obedience': 'obedient',
  'tame': 'tame',
  'vulnerable': 'vulnerable',
  'permanent': 'permanent',
  'adequate': 'adequate',
  'exhaustion': 'exhaust',
  'exhaust': 'exhaust',
  'complex': 'complex',
  'intelligent': 'intelligent',
  'intelligence': 'intelligent',

  // B3L9
  'pilgrimage': 'pilgrim',
  'pilgrim': 'pilgrim',
  'unify': 'unify',
  'exaggeration': 'exaggerate',
  'exaggerate': 'exaggerate',
  'undoubtedly': 'undoubtedly',
  'exact': 'exact',
  'authorities': 'authority',
  'authority': 'authority',
  'cast': 'cast',
  'devotion': 'devote',
  'devote': 'devote',
  'throng': 'throng',
  'explosive': 'explode',
  'explode': 'explode',
  'explosion': 'explode',
  'pierce': 'pierce',
  'emerge': 'emerge',
  'blessing': 'bless',
  'bless': 'bless',
  'kneel': 'kneel',
  'pavement': 'pavement',
  'hospitality': 'hospitality',
  'hospitable': 'hospitality',
  'enthusiastically': 'enthusiasm',
  'enthusiastic': 'enthusiasm',
  'enthusiasm': 'enthusiasm',
  'facilities': 'facility',
  'facility': 'facility',
  'accommodations': 'accommodate',
  'accommodate': 'accommodate',
  'religious': 'religion',
  'religion': 'religion',
  'humanity': 'humanity',
  'ritual': 'ritual',
  'designate': 'designate',
  'heritage': 'heritage',

  // B4L1
  'debate': 'debate',
  'penalty': 'penalty',
  'imprisonment': 'imprison',
  'imprison': 'imprison',
  'prison': 'imprison',
  'prisoner': 'imprison',
  'claim': 'claim',
  'insist': 'insist',
  'property': 'property',
  'companion': 'companion',
  'mental': 'mental',
  'devour': 'devour',
  'volume': 'volume',
  'acquire': 'acquire',
  'acquisition': 'acquire',
  'profound': 'profound',
  'wealthy': 'wealth',
  'wealth': 'wealth',
  'murder': 'murder',
  'murderer': 'murder',
  'disgust': 'disgust',
  'vain': 'vain',
  'worship': 'worship',
  'intention': 'intend',
  'intend': 'intend',
  'intentional': 'intend',
  'abandon': 'abandon',
  'surrender': 'surrender',
  'guilt': 'guilt',
  'guilty': 'guilt',
  'rumor': 'rumor',

  // B4L2
  'flood': 'flood',
  'flooding': 'flood',
  'appropriate': 'appropriate',
  'promising': 'promising',
  'arched': 'arch',
  'arch': 'arch',
  'solar': 'solar',
  'panel': 'panel',
  'install': 'install',
  'muddy': 'mud',
  'mud': 'mud',
  'session': 'session',
  'project': 'project',
  'practical': 'practical',
  'issue': 'issue',
  'nutrition': 'nutrition',
  'nutritious': 'nutrition',
  'hygiene': 'hygiene',
  'resistant': 'resist',
  'resist': 'resist',
  'resistance': 'resist',
  'productivity': 'productive',
  'productive': 'productive',
  'sufficient': 'sufficient',
  'income': 'income',
  'financial': 'finance',
  'finance': 'finance',
  'risk': 'risk',
  'geographical': 'geography',
  'geography': 'geography',
  'barrier': 'barrier',
  'indeed': 'indeed',
  'opportunity': 'opportunity',
  'severe': 'severe',

  // B4L3
  'progress': 'progress',
  'preservation': 'preserve',
  'preserve': 'preserve',
  'glimpse': 'glimpse',
  'identity': 'identity',
  'development': 'develop',
  'treasure': 'treasure',
  'replace': 'replace',
  'replacement': 'replace',
  'endanger': 'danger',
  'abundance': 'abundance',
  'abundant': 'abundance',
  'campaign': 'campaign',
  'conclude': 'conclude',
  'conclusion': 'conclude',
  'transport': 'transport',
  'transportation': 'transport',
  'situated': 'situate',
  'situate': 'situate',
  'drown': 'drown',
  'spare': 'spare',
  'priceless': 'price',
  'relieve': 'relieve',
  'relief': 'relieve',
  'urban': 'urban',
  'resident': 'resident',
  'residence': 'resident',
  'crucial': 'crucial',
  'urgent': 'urgent',
  'urgency': 'urgent',
  'enormous': 'enormous',
  'mission': 'mission',
  'fond': 'fond',

  // B4L4
  'adventurous': 'adventure',
  'adventure': 'adventure',
  'indigenous': 'indigenous',
  'tribe': 'tribe',
  'tribal': 'tribe',
  'span': 'span',
  'multiple': 'multiply',
  'multiply': 'multiply',
  'prosperous': 'prosper',
  'prosperity': 'prosper',
  'prosper': 'prosper',
  'plentiful': 'plenty',
  'plenty': 'plenty',
  'elaborate': 'elaborate',
  'appeal': 'appeal',
  'shallow': 'shallow',
  'species': 'species',
  'harmony': 'harmony',
  'harvest': 'harvest',
  'guarantee': 'guarantee',
  'guideline': 'guide',
  'private': 'private',
  'privacy': 'private',
  'sample': 'sample',
  'spoil': 'spoil',
  'consequence': 'consequence',
  'consequent': 'consequence',
  'dive': 'dive',
  'disturb': 'disturb',
  'disturbance': 'disturb',
  'wisdom': 'wisdom',
  'inhabitant': 'inhabit',
  'inhabit': 'inhabit',

  // B4L5
  'agent': 'agent',
  'agency': 'agent',
  'burst': 'burst',
  'arrest': 'arrest',
  'sigh': 'sigh',
  'compassionate': 'compassion',
  'compassion': 'compassion',
  'seize': 'seize',
  'starvation': 'starve',
  'seal': 'seal',
  'recruit': 'recruit',
  'colleague': 'colleague',
  'sneak': 'sneak',
  'isolated': 'isolate',
  'isolate': 'isolate',
  'isolation': 'isolate',
  'obtain': 'obtain',
  'convince': 'convince',
  'suitcase': 'suitcase',
  'sack': 'sack',
  'smuggle': 'smuggle',
  'smuggler': 'smuggle',
  'ambulance': 'ambulance',
  'courageous': 'courage',
  'execution': 'execute',
  'execute': 'execute',
  'fake': 'fake',
  'document': 'document',
  'selfless': 'self',
  'admit': 'admit',
  'bravery': 'brave',

  // B4L6
  'enterprise': 'enterprise',
  'transaction': 'transaction',
  'rate': 'rate',
  'merely': 'mere',
  'mere': 'mere',
  'accuracy': 'accurate',
  'suburb': 'suburb',
  'commute': 'commute',
  'commuter': 'commute',
  'network': 'network',
  'efficiency': 'efficient',
  'efficient': 'efficient',
  'roughly': 'rough',
  'rough': 'rough',
  'swiftly': 'swift',
  'swift': 'swift',
  'sort': 'sort',
  'load': 'load',
  'retrace': 'trace',
  'massive': 'massive',
  'handle': 'handle',
  'code': 'code',
  'particular': 'particular',
  'scheme': 'scheme',
  'tactic': 'tactic',
  'flawless': 'flaw',
  'flaw': 'flaw',
  'classic': 'classic',
  'classical': 'classic',
  'excellence': 'excellent',
  'excellent': 'excellent',

  // B4L7
  'gender': 'gender',
  'gap': 'gap',
  'population': 'population',
  'protest': 'protest',
  'injustice': 'justice',
  'justice': 'justice',
  'domestic': 'domestic',
  'chore': 'chore',
  'majority': 'majority',
  'chaos': 'chaos',
  'additionally': 'add',
  'addition': 'add',
  'additional': 'add',
  'nursery': 'nursery',
  'paralyze': 'paralyze',
  'council': 'council',
  'ban': 'ban',
  'discrimination': 'discriminate',
  'discriminate': 'discriminate',
  'democratic': 'democracy',
  'democracy': 'democracy',
  'anniversary': 'anniversary',
  'salary': 'salary',
  'tough': 'tough',
  'revolutionary': 'revolution',
  'revolution': 'revolution',
  'certificate': 'certificate',
  'strict': 'strict',
  'bold': 'bold',
  'eliminate': 'eliminate',
  'marvelous': 'marvel',
  'marvel': 'marvel',

  // B4L8
  'overflow': 'overflow',
  'narrow': 'narrow',
  'extent': 'extent',
  'decline': 'decline',
  'dramatically': 'drama',
  'dramatic': 'drama',
  'flock': 'flock',
  'expansion': 'expand',
  'expand': 'expand',
  'invasion': 'invade',
  'invade': 'invade',
  'complaint': 'complain',
  'complain': 'complain',
  'thoughtless': 'thought',
  'thoughtful': 'thought',
  'tenant': 'tenant',
  'landlord': 'landlord',
  'partial': 'partial',
  'rent': 'rent',
  'rental': 'rent',
  'option': 'option',
  'optional': 'option',
  'measure': 'measure',
  'measurable': 'measure',
  'measurement': 'measure',
  'license': 'license',
  'thorough': 'thorough',
  'strive': 'strive',
  'negative': 'negative',

  // B4L9
  'sin': 'sin',
  'widowed': 'widow',
  'widow': 'widow',
  'widower': 'widow',
  'appoint': 'appoint',
  'appointment': 'appoint',
  'accuse': 'accuse',
  'accusation': 'accuse',
  'assault': 'assault',
  'alcohol': 'alcohol',
  'alcoholic': 'alcohol',
  'despise': 'despise',
  'criticism': 'critic',
  'criticize': 'critic',
  'critical': 'critic',
  'critic': 'critic',
  'comfort': 'comfort',
  'version': 'version',
  'meanwhile': 'meanwhile',
  'instinctively': 'instinct',
  'instinctive': 'instinct',
  'instinct': 'instinct',
  'jury': 'jury',
  'despair': 'despair',
  'sensible': 'sensible',
  'moral': 'moral',
  'morality': 'moral',
  'sway': 'sway',
  'verdict': 'verdict',
  'victory': 'victory',
  'victor': 'victory',
  'definitely': 'definite',
  'definite': 'definite'
};

function getWordRoot(word: string): string {
  return wordFamilies[word] || word;
}

export function smartShuffle(array: VocabularyItem[], count: number): VocabularyItem[] {
  // Group words by their root form
  const wordGroups: Record<string, VocabularyItem[]> = {};
  
  array.forEach(item => {
    const root = getWordRoot(item.word);
    if (!wordGroups[root]) {
      wordGroups[root] = [];
    }
    wordGroups[root].push(item);
  });

  // Create shuffled result avoiding consecutive related words
  const result: VocabularyItem[] = [];
  const availableGroups = Object.keys(wordGroups);
  let lastUsedRoot: string | null = null;

  while (result.length < count && availableGroups.length > 0) {
    // Filter out the last used root to avoid consecutive related words
    const eligibleGroups = availableGroups.filter(root => root !== lastUsedRoot);
    
    // If no eligible groups, allow any group (fallback)
    const groupsToChooseFrom = eligibleGroups.length > 0 ? eligibleGroups : availableGroups;
    
    // Randomly select a group
    const randomGroupIndex = Math.floor(Math.random() * groupsToChooseFrom.length);
    const selectedRoot = groupsToChooseFrom[randomGroupIndex];
    const selectedGroup = wordGroups[selectedRoot];

    // Randomly select a word from the group
    const randomWordIndex = Math.floor(Math.random() * selectedGroup.length);
    const selectedWord = selectedGroup[randomWordIndex];

    result.push(selectedWord);
    lastUsedRoot = selectedRoot;

    // Remove the used word from its group
    selectedGroup.splice(randomWordIndex, 1);

    // Remove empty groups
    if (selectedGroup.length === 0) {
      delete wordGroups[selectedRoot];
      const groupIndex = availableGroups.indexOf(selectedRoot);
      if (groupIndex > -1) {
        availableGroups.splice(groupIndex, 1);
      }
    }
  }

  return result;
}
